import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Span from "../components/Span";
import ImageButton from "../components/ImageButton";
import Details from "../components/Details";
import StoreItem from "../components/StoreItem";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.notice}>
          30% of all sales from <Span>Kim's store</Span> will be donated to{" "}
          <Span>Give India</Span> as a part of{" "}
          <Span>COVID-19 Relief Fundraiser</Span>{" "}
        </div>
        <div className={styles.siteHeader}>
          <img
            src="/logo.png"
            srcset="/logo@2x.png 2x, /logo@3x.png 3x"
            className={styles.logo}
            alt="logo"
          />
          <ImageButton type="flat" action={() => {}}>
            <Image src="/shopping-bag.png" width="24" height="28" />
          </ImageButton>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.profile}>
          <div className={styles.social}>
            <img
              src="/profile-pic.jpg"
              alt="profile-pic"
              className={styles.profilePic}
            />
            <div className={styles.socialButtons}>
              <ImageButton type="raised" action={() => {}}>
                <Image src="/instagram.png" width="24" height="24" />
              </ImageButton>
              <ImageButton type="raised" action={() => {}}>
                <Image src="/share.png" width="24" height="24" />
              </ImageButton>
            </div>
          </div>

          <div className="userInfo">
            <h2>Neikimlhing (Kim)</h2>
            <div className="handle">@neikimlhing_</div>

            <Details summary="Keeping things whacky">
              Rem et eius explicabo eligendi. Non aut est possimus aut ea magni
              fuga et. Excepturi voluptas eaque fuga adipisci saepe autem sint.
              Accusamus nemo saepe et. Ut itaque doloremque accusantium nobis ea
              consequatur perspiciatis laboriosam. Ipsam et aut quo molestias.
            </Details>
          </div>
        </div>

        <div className={styles.store}>
          <h2 className={styles.storeHeading}>4 products listed</h2>

          <div className={styles.storeItems}>
            <StoreItem imgUrl="/camo/bitmap.png" />
            <StoreItem imgUrl="/camo/bitmap.png" />
            <StoreItem imgUrl="/camo/bitmap.png" />
            <StoreItem imgUrl="/camo/bitmap.png" />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.tagline}>
          <span>Take your sidehustle to a whole new level.</span>

          <div className={styles.instruction}>
            <span>Setup your own store.</span>
            <span>FOR FREE</span>
          </div>
        </div>

        <input placeholder="Your whatsapp number" />

        <button>GET INVITE</button>
      </footer>
    </div>
  );
}
